apiVersion: v1
kind: Service
metadata:
  name: {{ include "couchbase-cluster.fullname" . }}
  labels:
    app: {{ include "couchbase-cluster.fullname" . }}
    helm.sh/chart: {{ include "couchbase-cluster.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
  - name: http
    port: 8091
  - name: http1
    port: 8092
  - name: http2
    port: 8093
  - name: http3
    port: 8094
  - name: http4
    port: 11210
  # *.couchbase-cluster-a.default.svc.cluster.local
  #clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "couchbase-cluster.fullname" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "couchbase-cluster.fullname" . }}-ui
  labels:
    app: {{ include "couchbase-cluster.name" . }}-ui
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    #modify depends on your kubernetes integration LB type
spec:
  ports:
  - port: {{ .Values.spec.ports.port }}
    name: {{ include "couchbase-cluster.name" . }}
    targetPort: 8091
  - name: http1
    port: 8092
    targetPort: 8092
  - name: http2
    port: 8093
    targetPort: 8093
  - name: http3
    port: 8094
    targetPort: 8094
  - name: http4
    port: 11210
    targetPort: 11210
  selector:
    app.kubernetes.io/name: {{ include "couchbase-cluster.fullname" . }}
  sessionAffinity: ClientIP
  type: LoadBalancer
  loadBalancerIP: {{ .Values.spec.loadBalancerIP}}


